### ISSUE TITLE
some issue

### ISSUE THREAD

**Issue by milobluebell** [MCMainiac/PHPUBG#3]
hi, is this still in uptime?

**Comment by ricardoboss** [comment]
Sure. But the api may have changed by now. I'll have a look at this later.

**Comment by milobluebell** [comment]
but why my requests had be intercepted by cloudflare ddos protection(it says "checking your websites ......")? and it had sent me responses with HTTP503

**Comment by ricardoboss** [comment]
How did you get this response?

**Comment by milobluebell** [comment]
just request the api with curl.. 😄

**Comment by ricardoboss** [comment]
Look, 503 means the server is temporarily not available. Maybe you were just unlucky.

Since the tests pass (which use my API key and actually access the api to request data) I assume everything works fine. Maybe you want to add a test or so to check some functionality which currently is not working and we can start to debug the code.

**Comment by ricardoboss** [comment]
I'm closing this now.

**Comment by milobluebell** [comment]
k
