### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by egghyun** [MCMainiac/PHPUBG#4]
/test.php
/vendor/autoload.php
/vendor/mcmainiac

Fatal error: Class 'PHPUBG\PubgBuilder' not found in /home/bg/test.php on line 11

Why this problem?

**Comment by ricardoboss** [comment]
Please show the inside of your test.php.

**Comment by egghyun** [comment]
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

require __DIR__  . "/vendor/autoload.php";


use PHPUBG\Region;
use PHPUBG\PubgBuilder;

$statsEurope = PubgBuilder::setApiKey("your-api-key")
    ->getPlayer("MCMainiac")
    ->getStats(
        Region::get(Region::EUROPE)
    );

var_dump($statsEurope);
?>

**Comment by egghyun** [comment]
require __DIR__  . "/vendor/autoload.php";


use PHPUBG\Region;
use PHPUBG\PubgBuilder;

$statsEurope = PubgBuilder::setApiKey("your-api-key")
    ->getPlayer("MCMainiac")
    ->getStats(
        Region::get(Region::EUROPE)
    );

var_dump($statsEurope);

**Comment by ricardoboss** [comment]
You need to use `__DIR__` instead of `DIR` or the absolute path to the autoload without `DIR`.

Also do not forget to replace `"your-api-key" with your own API key.

I just had a look at the PUBG Tracker Network api and realised that I need to update some things... So even with a valid API key, this script won't work (even thou I didn't test it; maybe it works, no guarantee).
